In [1]:

%load_ext autoreload
%autoreload 2

In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('/home/jovyan/work/data/raw/beer_reviews.csv')

In [4]:
df.head()

,brewery_id,brewery_name,review_time,review_overall,review_aroma,review_appearance,review_profilename,beer_style,review_palate,review_taste,beer_name,beer_abv,beer_beerid
0,10325,Vecchio Birraio,1234817823,1.5,2.0,2.5,stcules,Hefeweizen,1.5,1.5,Sausa Weizen,5.0,47986
1,10325,Vecchio Birraio,1235915097,3.0,2.5,3.0,stcules,English Strong Ale,3.0,3.0,Red Moon,6.2,48213
2,10325,Vecchio Birraio,1235916604,3.0,2.5,3.0,stcules,Foreign / Export Stout,3.0,3.0,Black Horse Black Beer,6.5,48215
3,10325,Vecchio Birraio,1234725145,3.0,3.0,3.5,stcules,German Pilsener,2.5,3.0,Sausa Pils,5.0,47969
4,1075,Caldera Brewing Company,1293735206,4.0,4.5,4.0,johnmichaelsen,American Double / Imperial IPA,4.0,4.5,Cauldron DIPA,7.7,64883

In [5]:
df.shape

(1586614, 13)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 13 columns):
brewery_id            1586614 non-null int64
brewery_name          1586599 non-null object
review_time           1586614 non-null int64
review_overall        1586614 non-null float64
review_aroma          1586614 non-null float64
review_appearance     1586614 non-null float64
review_profilename    1586266 non-null object
beer_style            1586614 non-null object
review_palate         1586614 non-null float64
review_taste          1586614 non-null float64
beer_name             1586614 non-null object
beer_abv              1518829 non-null float64
beer_beerid           1586614 non-null int64
dtypes: float64(6), int64(3), object(4)
memory usage: 157.4+ MB

In [7]:
df.describe()

,brewery_id,review_time,review_overall,review_aroma,review_appearance,review_palate,review_taste,beer_abv,beer_beerid
count,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.586614e+06,1.518829e+06,1.586614e+06
mean,3.130099e+03,1.224089e+09,3.815581e+00,3.735636e+00,3.841642e+00,3.743701e+00,3.792860e+00,7.042387e+00,2.171279e+04
std,5.578104e+03,7.654427e+07,7.206219e-01,6.976167e-01,6.160928e-01,6.822184e-01,7.319696e-01,2.322526e+00,2.181834e+04
min,1.000000e+00,8.406720e+08,0.000000e+00,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e-02,3.000000e+00
25%,1.430000e+02,1.173224e+09,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,3.500000e+00,5.200000e+00,1.717000e+03
50%,4.290000e+02,1.239203e+09,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,6.500000e+00,1.390600e+04
75%,2.372000e+03,1.288568e+09,4.500000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.500000e+00,8.500000e+00,3.944100e+04
max,2.800300e+04,1.326285e+09,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.000000e+00,5.770000e+01,7.731700e+04

In [8]:
duplicate = df.duplicated()
print(duplicate.sum())

0

In [9]:
df.isnull().any().sum()

3

In [10]:
df.isnull().sum()

brewery_id                0
brewery_name             15
review_time               0
review_overall            0
review_aroma              0
review_appearance         0
review_profilename      348
beer_style                0
review_palate             0
review_taste              0
beer_name                 0
beer_abv              67785
beer_beerid               0
dtype: int64

In [11]:
df_cleaned = df.copy()

In [12]:
df_cleaned.drop('brewery_id', axis = 1, inplace = True)

In [13]:
df_cleaned.drop('beer_beerid', axis = 1, inplace = True)

In [14]:
df_cleaned.drop('beer_name', axis = 1, inplace = True)

In [15]:
df_cleaned.drop('beer_abv', axis = 1, inplace = True)

In [23]:
df_cleaned.drop('review_profilename', axis = 1, inplace = True)

In [24]:
#df_cleaned.drop('brewery_name', axis = 1, inplace = True)

cat_cols = ['brewery_name']

In [25]:
target_col = 'beer_style'

In [26]:
df_cleaned

,brewery_name,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,Vecchio Birraio,1234817823,1.5,2.0,2.5,Hefeweizen,1.5,1.5
1,Vecchio Birraio,1235915097,3.0,2.5,3.0,English Strong Ale,3.0,3.0
2,Vecchio Birraio,1235916604,3.0,2.5,3.0,Foreign / Export Stout,3.0,3.0
3,Vecchio Birraio,1234725145,3.0,3.0,3.5,German Pilsener,2.5,3.0
4,Caldera Brewing Company,1293735206,4.0,4.5,4.0,American Double / Imperial IPA,4.0,4.5
...,...,...,...,...,...,...,...,...
1586609,The Defiant Brewing Company,1162684892,5.0,4.0,3.5,Pumpkin Ale,4.0,4.0
1586610,The Defiant Brewing Company,1161048566,4.0,5.0,2.5,Pumpkin Ale,2.0,4.0
1586611,The Defiant Brewing Company,1160702513,4.5,3.5,3.0,Pumpkin Ale,3.5,4.0
1586612,The Defiant Brewing Company,1160023044,4.0,4.5,4.5,Pumpkin Ale,4.5,4.5
1586613,The Defiant Brewing Company,1160005319,5.0,4.5,4.5,Pumpkin Ale,4.5,4.5

In [27]:
num_cols = list(set(df_cleaned.columns) - (set(cat_cols) | set([target_col])))

In [28]:
num_cols

['review_overall',
 'review_taste',
 'review_aroma',
 'review_time',
 'review_palate',
 'review_appearance']

In [29]:
cat_cols

['brewery_name']

In [30]:
from src.data.sets import split_sets_random, save_sets, subset_x_y

In [31]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder

In [32]:
sc = StandardScaler()

In [33]:
df_cleaned[num_cols] = sc.fit_transform(df_cleaned[num_cols])

In [ ]:
import category_encoders as ce

In [36]:
encoder = ce.BinaryEncoder(cols=cat_cols)

In [37]:
encoder

BinaryEncoder(cols=['brewery_name'], drop_invariant=False,
              handle_missing='value', handle_unknown='value', mapping=None,
              return_df=True, verbose=0)

In [38]:
df_binary = encoder.fit_transform(df_cleaned)

In [39]:
df_binary

,brewery_name_0,brewery_name_1,brewery_name_2,brewery_name_3,brewery_name_4,brewery_name_5,brewery_name_6,brewery_name_7,brewery_name_8,brewery_name_9,...,brewery_name_11,brewery_name_12,brewery_name_13,review_time,review_overall,review_aroma,review_appearance,beer_style,review_palate,review_taste
0,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0.140161,-3.213310,-2.487952,-2.177663,Hefeweizen,-3.288833,-3.132454
1,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0.154496,-1.131774,-1.771225,-1.366096,English Strong Ale,-1.090123,-1.083188
2,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0.154516,-1.131774,-1.771225,-1.366096,Foreign / Export Stout,-1.090123,-1.083188
3,0,0,0,0,0,0,0,0,0,0,...,0,0,1,0.138951,-1.131774,-1.054499,-0.554530,German Pilsener,-1.823026,-1.083188
4,0,0,0,0,0,0,0,0,0,0,...,0,1,0,0.909878,0.255917,1.095679,0.257037,American Double / Imperial IPA,0.375684,0.966078
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1586609,0,1,0,1,1,0,0,1,1,0,...,0,0,1,-0.802208,1.643608,0.378953,-0.554530,Pumpkin Ale,0.375684,0.282989
1586610,0,1,0,1,1,0,0,1,1,0,...,0,0,1,-0.823585,0.255917,1.812405,-2.177663,Pumpkin Ale,-2.555929,0.282989
1586611,0,1,0,1,1,0,0,1,1,0,...,0,0,1,-0.828106,0.949762,-0.337773,-1.366096,Pumpkin Ale,-0.357219,0.282989
1586612,0,1,0,1,1,0,0,1,1,0,...,0,0,1,-0.836983,0.255917,1.095679,1.068603,Pumpkin Ale,1.108588,0.966078
1586613,0,1,0,1,1,0,0,1,1,0,...,0,0,1,-0.837215,1.643608,1.095679,1.068603,Pumpkin Ale,1.108588,0.966078

In [41]:
df_binary['beer_style'] = df_binary['beer_style'].astype('category')
df_binary['beer_style'] = df_binary['beer_style'].cat.codes

In [42]:
df_binary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1586614 entries, 0 to 1586613
Data columns (total 21 columns):
brewery_name_0       1586614 non-null int64
brewery_name_1       1586614 non-null int64
brewery_name_2       1586614 non-null int64
brewery_name_3       1586614 non-null int64
brewery_name_4       1586614 non-null int64
brewery_name_5       1586614 non-null int64
brewery_name_6       1586614 non-null int64
brewery_name_7       1586614 non-null int64
brewery_name_8       1586614 non-null int64
brewery_name_9       1586614 non-null int64
brewery_name_10      1586614 non-null int64
brewery_name_11      1586614 non-null int64
brewery_name_12      1586614 non-null int64
brewery_name_13      1586614 non-null int64
review_time          1586614 non-null float64
review_overall       1586614 non-null float64
review_aroma         1586614 non-null float64
review_appearance    1586614 non-null float64
beer_style           1586614 non-null int8
review_palate        1586614 non-null float64
review_taste         1586614 non-null float64
dtypes: float64(6), int64(14), int8(1)
memory usage: 243.6 MB

In [43]:
X_train, y_train, X_val, y_val, X_test, y_test = split_sets_random(df_binary, target_col=target_col, test_ratio=0.2, to_numpy=True)

In [44]:
save_sets(X_train=X_train, y_train=y_train, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, path='/home/jovyan/work/data/processed/beer_style/')

In [45]:
from src.models.pytorch import PytorchDataset

train_dataset = PytorchDataset(X=X_train, y=y_train)
val_dataset = PytorchDataset(X=X_val, y=y_val)
test_dataset = PytorchDataset(X=X_test, y=y_test)

In [46]:
from src.models.null import NullModel

In [47]:
baseline_model = NullModel(target_type='classification')
y_base = baseline_model.fit_predict(y_train)

In [48]:
from src.models.performance import print_class_perf

In [49]:
print_class_perf(y_base, y_train, set_name='Training', average='weighted')

Accuracy Training: 0.0742157299405022
F1 Training: 0.01025487603110527

In [50]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [51]:
from src.models.pytorch import PytorchMultiClass

model = PytorchMultiClass(X_train.shape[1])

In [52]:
from src.models.pytorch import get_device

device = get_device()
model.to(device)

PytorchMultiClass(
  (layer_1): Linear(in_features=20, out_features=32, bias=True)
  (layer_out): Linear(in_features=32, out_features=104, bias=True)
  (softmax): Softmax(dim=1)
)

In [53]:
print(model)

PytorchMultiClass(
  (layer_1): Linear(in_features=20, out_features=32, bias=True)
  (layer_out): Linear(in_features=32, out_features=104, bias=True)
  (softmax): Softmax(dim=1)
)

In [54]:
criterion = nn.CrossEntropyLoss()

In [55]:
from torch.utils.data import Dataset, DataLoader

In [56]:
optimizer = torch.optim.Adam(model.parameters(), lr=0.1)

In [57]:
def train_classification(train_data, model, criterion, optimizer, batch_size, device, scheduler=None, generate_batch=None):
    """Train a Pytorch multi-class classification model

    Parameters
    ----------
    train_data : torch.utils.data.Dataset
        Pytorch dataset
    model: torch.nn.Module
        Pytorch Model
    criterion: function
        Loss function
    optimizer: torch.optim
        Optimizer
    bacth_size : int
        Number of observations per batch
    device : str
        Name of the device used for the model
    scheduler : torch.optim.lr_scheduler
        Pytorch Scheduler used for updating learning rate
    collate_fn : function
        Function defining required pre-processing steps

    Returns
    -------
    Float
        Loss score
    Float:
        Accuracy Score
    """
    
    # Set model to training mode
    model.train()
    train_loss = 0
    train_acc = 0
    
    # Create data loader
    data = DataLoader(train_data, batch_size=batch_size, shuffle=True, collate_fn=generate_batch)
    
    # Iterate through data by batch of observations
    for feature, target_class in data:

        # Reset gradients
        optimizer.zero_grad()
        
        # Load data to specified device
        feature, target_class = feature.to(device), target_class.to(device)
        
        # Make predictions
        output = model(feature)
        
        # Calculate loss for given batch
        loss = criterion(output, target_class.long())

        # Calculate global loss
        train_loss += loss.item()
        
        # Calculate gradients
        loss.backward()

        # Update Weights
        optimizer.step()
        
        # Calculate global accuracy
        train_acc += (output.argmax(1) == target_class).sum().item()

    # Adjust the learning rate
    if scheduler:
        scheduler.step()

    return train_loss / len(train_data), train_acc / len(train_data)

In [58]:
def test_classification(test_data, model, criterion, batch_size, device, generate_batch=None):
    """Calculate performance of a Pytorch multi-class classification model

    Parameters
    ----------
    test_data : torch.utils.data.Dataset
        Pytorch dataset
    model: torch.nn.Module
        Pytorch Model
    criterion: function
        Loss function
    bacth_size : int
        Number of observations per batch
    device : str
        Name of the device used for the model
    collate_fn : function
        Function defining required pre-processing steps

    Returns
    -------
    Float
        Loss score
    Float:
        Accuracy Score
    """    
    
    # Set model to evaluation mode
    model.eval()
    test_loss = 0
    test_acc = 0
    
    # Create data loader
    data = DataLoader(test_data, batch_size=batch_size, collate_fn=generate_batch)
    
    # Iterate through data by batch of observations
    for feature, target_class in data:
        
        # Load data to specified device
        feature, target_class = feature.to(device), target_class.to(device)
        
        # Set no update to gradients
        with torch.no_grad():
            
            # Make predictions
            output = model(feature)
            
            # Calculate loss for given batch
            loss = criterion(output, target_class.long())

            # Calculate global loss
            test_loss += loss.item()
            
            # Calculate global accuracy
            test_acc += (output.argmax(1) == target_class).sum().item()

    return test_loss / len(test_data), test_acc / len(test_data)

In [59]:
N_EPOCHS = 50
BATCH_SIZE = 32

In [60]:
for epoch in range(N_EPOCHS):
    train_loss, train_acc = train_classification(train_dataset, model=model, criterion=criterion, optimizer=optimizer, batch_size=BATCH_SIZE, device=device)
    valid_loss, valid_acc = test_classification(val_dataset, model=model, criterion=criterion, batch_size=BATCH_SIZE, device=device)

    print(f'Epoch: {epoch}')
    print(f'\t(train)\t|\tLoss: {train_loss:.4f}\t|\tAcc: {train_acc * 100:.1f}%')
    print(f'\t(valid)\t|\tLoss: {valid_loss:.4f}\t|\tAcc: {valid_acc * 100:.1f}%')

Epoch: 0
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 1
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 2
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 3
	(train)	|	Loss: 0.1434	|	Acc: 7.3%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 4
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 5
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 6
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 7
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 8
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 9
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 10
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 11
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 12
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 13
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 14
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 15
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 16
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 17
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 18
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 19
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 20
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 21
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 22
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 23
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 24
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 25
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 26
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 27
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 28
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 29
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 30
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 31
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 32
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 33
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 34
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 35
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 36
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 37
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 38
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 39
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 40
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 41
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 42
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 43
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 44
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 45
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 46
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 47
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 48
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%
Epoch: 49
	(train)	|	Loss: 0.1433	|	Acc: 7.4%
	(valid)	|	Loss: 0.1433	|	Acc: 7.4%

In [61]:
torch.save(model, "/home/jovyan/work/models/pytorch_beer_style.pt")

In [62]:
#list(model.parameters())[4].shape

In [63]:
test_loss, test_acc = test_classification(test_dataset, model=model, criterion=criterion, batch_size=BATCH_SIZE, device=device)
print(f'\tLoss: {test_loss:.4f}\t|\tAccuracy: {test_acc:.1f}')

	Loss: 0.1434	|	Accuracy: 0.1